basic_app/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static

#Temlpate Tagging

app_name = 'basic_app'

urlpatterns = [
    path('register/', views.register, name='register'),
    path('user_login/', views.user_login, name='user_login'),
    path('user_logout/', views.user_logout, name='user_logout'),
    
    path('photo_list/', views.PhotoListView.as_view(), name='photo_list'),
    path('profile/<int:pk>/', views.Profile.as_view(), name='profile'),

    path("photo_delete/<int:pk>/",views.PhotoDeleteView.as_view(),name='photo_delete'),
    path("photo_upload/",views.PhotoUploadView,name='upload_photo'),
]  + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

learn_users_django/urls.py
from django.contrib import admin
from django.urls import path,include
from basic_app import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.PhotoListView.as_view(), name='index'),
    path('basic_app/', include('basic_app.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

basic_app/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse


# Create your models here.


class UserProfileInfo(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
   
    def __str__(self):
        return self.user.username




class Photo(models.Model):
    user = models.ForeignKey(User, related_name='photos', on_delete=models.CASCADE)
    site = models.URLField(blank=True, null=True)
    pic = models.ImageField(upload_to='profile_pics',blank=True)
    pic_Number = models.PositiveIntegerField(blank=True, null=True)
    Description = models.TextField(blank=True, null=True)
    
    def __str__(self):
        return self.site
    
    def get_absolute_url(self):
        return reverse('basic_app:photo_list')
    

basic_app/forms.py
from django import forms
from django.contrib.auth.models import User
from .models import Photo



class UserForm(forms.ModelForm):
    password = forms.CharField(widget = forms.PasswordInput())
    
    class Meta():
        model = User
        fields = ('first_name','last_name','username','email','password')





class PhotoForm(forms.ModelForm):

    class Meta():
        model = Photo
        fields = '__all__'

basic_app/views.py
from django.shortcuts import render
from basic_app.forms import UserForm
from django.views.generic import ListView
from .models import UserProfileInfo, Photo
from django.views.generic import ListView, CreateView, DeleteView, DetailView
from django.contrib.auth.models import User
from .forms import PhotoForm

from django.urls import reverse,reverse_lazy
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect, HttpResponse
from django.contrib.auth import authenticate,login,logout


# Create your views here. 


class Profile(DetailView):
    model = User





def register(request):
    registered = False
    
    if request.method == 'POST':
        
        user_form = UserForm(data=request.POST)
        
        
        if user_form.is_valid():
            
            user = user_form.save()
            user.set_password(user.password)
            user.save()
            
            registered = True

        else:
            print(user_form.errors)
    
    
    else:
        user_form = UserForm()
            
    
    
    return render(request,'basic_app/register.html',{
        'user_form':user_form,
        'registered':registered,
    })





def user_login(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        
        user = authenticate(username=username, password=password)
        
        if user:
            if user.is_active:
                login(request,user)
                return HttpResponseRedirect(reverse('index'))
            else:
                return HttpResponse('account is not active')
        
        else:
            print('someone tried to login but field!')
            print('username : {} and password: {}'.format(username,password))
            return HttpResponse('invalid login details supplied!')
        
    else:
        return render(request,'basic_app/login.html', {})




@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('index'))






class PhotoListView(ListView):
    model = Photo







class PhotoDeleteView(DeleteView):
    model = Photo
    success_url = reverse_lazy('basic_app:photo_list')


















@login_required
def PhotoUploadView(request):
    if request.method == 'POST':
        form = PhotoForm(request.POST, request.FILES)
        if form.is_valid():
            # file is saved
            form.save()
            return HttpResponseRedirect(reverse('basic_app:photo_list'))
    else:
        form = PhotoForm()
    return render(request, 'basic_app/upload_photo.html', {'form': form})

templates/basic_app/base.html
<!DOCTYPE html>
<html>
<head>
	<title></title>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
	
</head>

<body>


	<div class="container">
	<div class="jumbotron">


    <nav class="nav navbar navbar-expand-lg navbar-light bg-light">
    	<div class="collapse navbar-collapse" id="navbarNav">
        	<ul class="navbar-nav">

				<li class="nav-link"><a href="{% url 'index' %}">Home</a></li>
				<li class="nav-link"><a href="{% url 'admin:index' %}">Admin</a></li>
				<li class="nav-link"><a href="{% url 'basic_app:register' %}">Register</a></li>

				{% if user.is_authenticated %}
				<li class="nav-link"><a href="{% url 'basic_app:user_logout' %}">Logout</a></li>
				<li class="nav-link"><a href="{% url 'basic_app:profile' pk=user.pk %}">Your Photos</a></li>
				<li class="nav-link"><a href="{% url 'basic_app:upload_photo' %}">Add a new photo to the Wall</a></li>
				{% else %}
				<li class="nav-link"><a href="{% url 'basic_app:user_login' %}">Login</a></li>
				{% endif %}
			</ul>
		</div>
	</nav>


	</div>
	</div>


	<div class="container">
		{% block body_block %}
        
        {% endblock body_block %}
	</div>
</body>







</html>

templates/basic_app/login.html
<!DOCTYPE html>
{% extends "basic_app/base.html" %}
	{% block body_block %}

		<div class="jumbotron">
			<h1>Please Login</h1>
            <form method="post" action="{% url 'basic_app:user_login' %}">
            	    {% csrf_token %}
                    <label for="username">Username:</label>
                    <input type="text" name="username" placeholder="Enter your username">

                    <label for="password">Password:</label>
                    <input type="text" name="password">

                    <input type="submit" name="" value="Login">
            	</form>
		</div>

	{% endblock body_block %}

templates/basic_app/photo_confirm_delete.html
{% extends "basic_app/base.html" %}
	{% block body_block %}

        <h1>Delete Photo of ' {{photo.site}} '  ?</h1>

        <form method="post">
        {% csrf_token %}
        <input type="submit" value="Delete">
        <a href='{% url 'index' %}'>Cancel</a>
        </form>


	{% endblock body_block %}

templates/basic_app/photo_list.html
{% extends "basic_app/base.html" %}
	{% block body_block %}

    {% for photo in photo_list %}

    <a href="{{photo.site}}"><img src="{{MEDIA_URL}}{{photo.pic}}" alt="{{photo.Description}}" width="100" height="100" ></a>

    {% endfor %}

	{% endblock body_block %}


    

templates/basic_app/register.html
<!DOCTYPE html>
{% extends "basic_app/base.html" %}
{% load static %}
	{% block body_block %}

		<div class="jumbotron">
            {% if registered %}
            	<h1>Thank you for registration !</h1>                
            {% else %}
            	<h1>You can register here !</h1>
            	<h1>Please fill out the form:</h1>

            	<form method="post" enctype="multipart/form-data">
            	    {% csrf_token %}
                    {{ user_form.as_p }}
                    <input type="submit" name="" value="Register">
            	</form>


            {% endif %}
		</div>

	{% endblock body_block %}

templates/basic_app/upload_photo.html
<!DOCTYPE html>
{% extends "basic_app/base.html" %}
{% load static %}
	{% block body_block %}

		<div class="jumbotron">

            	<form method="post" enctype="multipart/form-data">
            	    {% csrf_token %}
                    {{ form.as_p }}
                    <input type="submit" name="" value="submit">
            	</form>

		</div>

	{% endblock body_block %}